name: interview_mockup
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #Internationalisation
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0

  #UI
  auto_size_text: 3.0.0
  sizer: 2.0.15
  flutter_svg: 1.1.4
  fluttertoast: 8.1.1

  #State Management
  flutter_bloc: 8.1.1

  #Testing
  device_preview: 1.1.0
  logger: 1.1.0

  # API requests
  http: 0.13.5

  #Permissions
  permission_handler: 10.0.0

  #Files
  path_provider: ^2.0.11
  file_picker: ^5.2.5


  #databases
  hive: 2.2.3
  equatable: 2.0.5

  # functionality
  pdf_text: ^0.5.0
  text_to_speech: ^0.2.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon_logo.png"
  color: "#ffF3F5F6"


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/business/localizations/lang/en.json
    - lib/business/localizations/lang/fr.json
    - assets/svg/
    - assets/svg/navigation_icons/
    - assets/images/
    - assets/pdf/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Black.ttf
        - asset: assets/fonts/Urbanist/Urbanist-BlackItalic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
        - asset: assets/fonts/Urbanist/Urbanist-BoldItalic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-ExtraBold.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf